#!/bin/bash

getContent() {
    if [ -f "$1" ]; then
        content=$(<$1)
        echo "$content"
    else
        echo "File '$1' not found."
        exit 1
    fi
}

runFile() {
    python "$1"
}

delFile() {
    if [ -f "$1" ]; then
        rm "$1"
    fi
}

write() {
    echo "$2" > "$1"
}

translate() {
    content=$(echo "$1" | sed -e 's/{/:/g' -e 's/}//g' -e 's/;/\n/g' -e 's/def script()/if __name__ == "__main__"/g')
    echo "$content"
}

main() {
    if [ $# -ne 1 ]; then
        echo "Usage: $0 <filename>"
        exit 1
    fi

    filename=$1
    code=$(getContent "$filename")
    if [ ! -z "$code" ]; then
        code=$(translate "$code")
        write "cpyrunner.py" "$code"
        runFile "cpyrunner.py"
    else
        echo "Exiting due to missing file."
    fi

    delFile "cpyrunner.py"
}

main "$@"
